### ISSUE TITLE
libsecp256k1 library failed to load

### ISSUE THREAD

**Issue by Saint1166** [ASeriousMister/SeedCheck.py#1]
i'm getting this error when i tried to to run it,please what do i need to do to fix this?

libsecp256k1 library failed to load. exceptions: [OSError('/home/saint/SeedCheck.py/electrum/libsecp256k1.so.0: cannot open shared object file: No such file or directory'), OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory')]
Error: Failed to load libsecp256k1.

**Comment by ASeriousMister** [comment]
Hello. You need to install Electrum's dependencies. Use this command, as stated in the readme.md instructions: sudo apt install python3-pyqt5 libsecp256k1-0 python3-cryptography
It works with ubuntu (both 20.04 and 22.04) and should work with other distros using apt. Adapt the sintax if you are using other distros.
Do not hesitate to contact me if you need other help.

**Comment by Saint1166** [comment]
i did everything needed but still the same,i'm on Kali linux

**Comment by Saint1166** [comment]
i got passed it,thank you
